version: "3.7"
services:
  app:
    build: .
    container_name: my_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/database
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DDL-AUTO: create 
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - ./data/:/var/lib/mysql
    


