# Use root/example as user/password credentials
version: '3.1'

services:

  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: pwd
      MARIADB_DATABASE: database
      MARIADB_USER: user
      MARIADB_PASSWORD: password

    volumes:
      - ./data:/var/lib/mysql
      

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080