version: '3.3'
services:
  # add the mariadb service
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  
  # Optional GUI for mariadb
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080